name: build-cv

on:
  pull_request:
  push:
    banches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup caching for tectonic
        uses: actions/cache@v3
        with:
          path: ~/.cache/Tectonic
          key: tectonic-${{ runner.os }}

      - name: Setup caching for conda packages
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}

      - name: Setup miniconda with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
            environment-file: environment.yml
          activate-environment: cv
          miniforge-variant: Mambaforge
          miniforge-version: "latest"
          use-mamba: true
          channel-priority: strict
          # Needed for caching
          use-only-tar-bz2: true

      - name: List installed packages
        shell: bash -el {0}
        run: mamba list

      - name: Build cv
        shell: bash -el {0}
        run: |
          make all
          touch _output/.nojekyll

      - name: Deploy 🚀
        if: success() && github.event_name == 'push'
        # Don't use tags: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        uses: JamesIves/github-pages-deploy-action@049a95c516cd5723d8cfde79dc7a79fcdcbd6c97
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build
